# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1493721570);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1493721690);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1493886475);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1493721450);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1493721330);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/home/pavan/Desktop");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150922181813");
user_pref("browser.slowStartup.averageTime", 703);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20150922181813");
user_pref("browser.startup.homepage_override.mstone", "38.3.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1483089806862");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1493886417931");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1493886420220");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1493972820220");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1482934734942");
user_pref("datareporting.policy.firstRunTime", "1482934673797");
user_pref("datareporting.sessions.current.activeTicks", 9);
user_pref("datareporting.sessions.current.firstPaint", 619);
user_pref("datareporting.sessions.current.main", 121);
user_pref("datareporting.sessions.current.sessionRestored", 851);
user_pref("datareporting.sessions.current.startTime", "1493886354950");
user_pref("datareporting.sessions.current.totalTime", 54);
user_pref("datareporting.sessions.currentIndex", 10);
user_pref("datareporting.sessions.prunedIndex", 9);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 13);
user_pref("extensions.blocklist.pingCountVersion", 13);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.3.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1493635173);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.3.0");
user_pref("extensions.lastPlatformVersion", "38.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.3.0\",\"st\":1482932656000,\"mt\":1442946543000}}}");
user_pref("gecko.buildID", "20150922181813");
user_pref("gecko.mstone", "38.3.0");
user_pref("idle.lastDailyNotification", 1493886584);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1483444851);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20150922181813");
user_pref("media.gmp-manager.lastCheck", 1493886418);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1493886418);
user_pref("places.history.expiration.transient_current_max_pages", 89573);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1492691684);
user_pref("toolkit.startup.last_success", 1493886355);
user_pref("toolkit.telemetry.previousBuildID", "20150922181813");
